# https://github.com/ppggff/vagrant-qemu
Vagrant.configure("2") do |config|
  
  config.vm.box = "centos/7"

  config.vm.provider "qemu" do |qe|
    qe.arch = "x86_64"
    qe.machine = "q35"
    qe.cpu = "max"
    qe.net_device = "virtio-net-pci"
    qe.ssh_port = 2222
  end

  username = ENV["ansible"]
  (1..1).each do |i|
    config.vm.define "local_linux-0#{i}" do |node|
      node.vm.network "private_network", ip: "33.33.33.3#{i}"
      node.vm.hostname = "local-linux-0#{i}"
    end
  end

  ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa_global_five9lab.pub").first.strip
  config.vm.provision 'shell', inline: 'mkdir -p /root/.ssh'
  config.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /root/.ssh/authorized_keys"
  config.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys", privileged: false
  config.vm.provision "shell", inline: <<-SHELL
    sed -i 's/gpgcheck=1/gpgcheck=0/g' /etc/yum.repos.d/*
    yum -y install python3 git
    sudo sed -i 's/without-password/yes/g' /etc/ssh/sshd_config
    sudo sed -i /etc/sudoers -re 's/^root.*/root ALL=(ALL:ALL) NOPASSWD: ALL/g'
    echo "vagrant ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
    sudo systemctl restart sshd
  SHELL
end
